[install]
linker = "isolated"
# minimumReleaseAge = 259200 # 3 days in seconds
minimumReleaseAgeExcludes = []

## Disabling security scanner for now, as it frequently times-out
# [install.security]
# scanner = "@socketsecurity/bun-security-scanner"
